"""empty message

Revision ID: 5c76bc203eb2
Revises: ba289ee11bd5
Create Date: 2025-05-02 14:13:54.438278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c76bc203eb2'
down_revision = 'ba289ee11bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('album_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('artist_ids', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('artist_ids')
        batch_op.drop_column('album_id')
        batch_op.drop_column('album')

    # ### end Alembic commands ###
